
package cn.itcast.crm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.itcast.cn/")
@XmlSeeAlso({
    //ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activeAccount", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.ActiveAccount")
    @ResponseWrapper(localName = "activeAccountResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.ActiveAccountResponse")
    public void activeAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "associationFixedAreaId2Customer", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.AssociationFixedAreaId2Customer")
    @ResponseWrapper(localName = "associationFixedAreaId2CustomerResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.AssociationFixedAreaId2CustomerResponse")
    public void associationFixedAreaId2Customer(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHasAssociation", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindHasAssociation")
    @ResponseWrapper(localName = "findHasAssociationResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindHasAssociationResponse")
    public List<Customer> findHasAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssociation", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindNotAssociation")
    @ResponseWrapper(localName = "findNotAssociationResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindNotAssociationResponse")
    public List<Customer> findNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.itcast.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginByUsername", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.LoginByUsername")
    @ResponseWrapper(localName = "loginByUsernameResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.LoginByUsernameResponse")
    public Customer loginByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itcast.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.itcast.cn/", className = "cn.itcast.crm.service.FindAllResponse")
    public List<Customer> findAll();

}
